### ISSUE TITLE
No matching distribution found for onnxruntime-gpu

### ISSUE THREAD

**Issue by genkio** [jim60105/docker-whisperX#12]
Couldn't run `docker build --build-arg LANG=ja --build-arg WHISPER_MODEL=large-v2 -t whisperx:large-v2-ja .` on Mac M1 Pro 😭

<details>

 > [dependencies 7/7] RUN --mount=type=cache,target=/root/.cache/pip pip install /code:
0.246 Processing /code
0.247   Installing build dependencies: started
0.967   Installing build dependencies: finished with status 'done'
0.968   Getting requirements to build wheel: started
1.066   Getting requirements to build wheel: finished with status 'done'
1.067   Preparing metadata (pyproject.toml): started
1.160   Preparing metadata (pyproject.toml): finished with status 'done'
1.164 Requirement already satisfied: torch>=2 in /venv/lib/python3.10/site-packages (from whisperx==3.1.1) (2.1.0)
1.165 Requirement already satisfied: torchaudio>=2 in /venv/lib/python3.10/site-packages (from whisperx==3.1.1) (2.1.0)
1.223 Collecting faster-whisper>=0.8 (from whisperx==3.1.1)
1.224   Using cached faster_whisper-0.9.0-py3-none-any.whl.metadata (11 kB)
1.254 Collecting transformers (from whisperx==3.1.1)
1.255   Using cached transformers-4.34.1-py3-none-any.whl.metadata (121 kB)
1.269 Collecting ffmpeg-python>=0.2 (from whisperx==3.1.1)
1.270   Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
1.372 Collecting pandas (from whisperx==3.1.1)
1.373   Using cached pandas-2.1.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (18 kB)
1.374 Requirement already satisfied: setuptools>=65 in /venv/lib/python3.10/site-packages (from whisperx==3.1.1) (68.2.2)
1.389 Collecting nltk (from whisperx==3.1.1)
1.390   Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
1.408 Collecting pyannote.audio==3.0.1 (from whisperx==3.1.1)
1.409   Using cached pyannote.audio-3.0.1-py2.py3-none-any.whl.metadata (7.8 kB)
1.509 Collecting asteroid-filterbanks>=0.4 (from pyannote.audio==3.0.1->whisperx==3.1.1)
1.510   Using cached asteroid_filterbanks-0.4.0-py3-none-any.whl (29 kB)
1.524 Collecting einops>=0.6.0 (from pyannote.audio==3.0.1->whisperx==3.1.1)
1.525   Using cached einops-0.7.0-py3-none-any.whl.metadata (13 kB)
1.550 Collecting huggingface-hub>=0.13.0 (from pyannote.audio==3.0.1->whisperx==3.1.1)
1.551   Using cached huggingface_hub-0.18.0-py3-none-any.whl.metadata (13 kB)
1.746 Collecting lightning>=2.0.1 (from pyannote.audio==3.0.1->whisperx==3.1.1)
1.747   Using cached lightning-2.1.0-py3-none-any.whl.metadata (64 kB)
1.789 Collecting omegaconf<3.0,>=2.1 (from pyannote.audio==3.0.1->whisperx==3.1.1)
1.790   Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
1.812 INFO: pip is looking at multiple versions of pyannote-audio to determine which version is compatible with other requirements. This could take a while.
1.813 ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu>=1.16.0 (from pyannote-audio) (from versions: none)
1.813 ERROR: No matching distribution found for onnxruntime-gpu>=1.16.0
------
Dockerfile:21
--------------------
  19 |     # Install whisperX
  20 |     COPY ./whisperX /code
  21 | >>> RUN --mount=type=cache,target=/root/.cache/pip pip install /code
  22 |
  23 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install /code" did not complete successfully: exit code: 1

</details>

**Comment by jim60105** [comment]
According to your error log, pip cannot find a matching package.
The installation dependencies are defined by the whisperX project. ~~If you think it is an error, please raise an issue in the whisperX project (or pyannote-audio and onnxruntime-gpu project).~~
I found an issue here: https://github.com/m-bain/whisperX/issues/540

**Comment by jim60105** [comment]
Close this issue because it is unrelated to this repository.
