### ISSUE TITLE
Missing libraries in Docker for current `main` state

### ISSUE THREAD

**Issue by stex** [jim60105/docker-whisperX#14]
Hey :) 

Thanks a lot for this project and the images!

Just wanted to let you know that I had to add the following libraries to build the current `Dockerfile` on an M1 macbook: `libgomp1 libsndfile1`

**Comment by jim60105** [comment]
Thank you for your suggestion. I have already added the linux/arm64 images.
However, I do not have an M1 machine to confirm if it is working properly.
Please let me know if there are any further issues.
