### ISSUE TITLE
is diarization using gpu or cpu ?

### ISSUE THREAD

**Issue by MyraBaba** [jim60105/docker-whisperX#18]
Hi,

docker succesfully transcribe the wavs. but when I add --diarize it takes too long. and no gpu activity only cpu ?

is diarization suffers the latest whisperx pyannote 3.0.1 cpu/gpu problem ?

How we can solve the diarize that should use the gpu instead of cpu ?

Best

**Comment by jim60105** [comment]
This project will automatically synchronize with the WhisperX master branch once a week, and of course it will have the same issues.
For any issues unrelated to dockerize, please [raise them in the WhisperX project](https://github.com/m-bain/whisperX/issues).

I'm not sure, but https://github.com/m-bain/whisperX/issues/499 and https://github.com/m-bain/whisperX/issues/542 might be what you're looking for.
