### ISSUE TITLE
Versioned Images

### ISSUE THREAD

**Issue by randyburden** [jim60105/docker-whisperX#28]
What are your thoughts on adding versioning to the pre-built Docker images?

For example, I had a working solution a few days ago, but when I ran my same code today I ran into issue #27. If the Docker images were versioned, then I could "pin" my code to use a specific version and know that each time it runs it will work reliably. I would then have the flexibility to upgrade to a new version when I have time.

Today, I'm running a command such as:
```bash
docker run --gpus all -it -v ".:/app" ghcr.io/jim60105/whisperx:small-en -- --diarize --hf_token "XXXXX" audio.mp3
```

What I'm proposing is adding a Timestamp or version number to the pre-built images such as  `ghcr.io/jim60105/whisperx:small-en-2023-11-30T02-03-33` or something similar so that I could target a specific version of a pre-built image.

If something like that already exists please let me know. Also, thank you for putting together this project as it greatly simplifies getting WhisperX up and running. 🙂

**Comment by jim60105** [comment]
I'm sorry that I made mistakes when refactoring the Dockerfile.

If you need a specific image you can pull it by digest
https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier

This project is built once a week, and if timestamps are added, it will eventually be filled with tags.
If I were to add versioning, I would prefer to align it with the release version number of WhisperX. Nevertheless, it is worth noting that WhisperX has not publish a new version in the past months, and there are notable disparities between the latest version and the master branch.

Therefore, I will reject this proposal.

**Comment by randyburden** [comment]
@jim60105, thanks, I wasn't aware of the ability to pull images by digest. 👍
