### ISSUE TITLE
Permission denied: '/app/database.yml'

### ISSUE THREAD

**Issue by Winger-Wang** [jim60105/docker-whisperX#31]
I am running the docker in root, and when trying to run the image I ran into an error `PermissionError: [Errno 13] Permission denied: '/app/database.yml'`. Details in the screenshot below. 

I am running with nvidia driver 535 and CUDA 12.2 on Ubuntu 22.04 

<img width="1033" alt="Screenshot 2023-12-19 at 22 14 51" src="https://github.com/jim60105/docker-whisperX/assets/115909333/8cf144b1-645a-446f-976c-a122e9679dd8">

**Comment by jim60105** [comment]
When your host is Linux, mounted folder permissions **_WILL_** affect to the permissions in the container. I use `1001:1001` in these containers.

You can find more information in these blogs, they mention the situation you encountered and how to handle this problem.
- https://mydeveloperplanet.com/2022/10/19/docker-files-and-volumes-permission-denied/
- https://medium.com/@nielssj/docker-volumes-and-file-system-permissions-772c1aee23ca

And, why I write the images with non-root users:
- https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security

I personally use Windows as the host and am not familiar with actual processing on Linux host. Please let me know if these can solve your problem.

**Comment by Winger-Wang** [comment]
Thanks for your help! I have corrected the permission setting and it runs smoothly. I originally thought it a problem with dockerd instead one with the mounted folder. I guess it's more of a beginner's mistake. 

Thank you so much for providing detailed explanation on this topic. I have really learned a lot.
