### ISSUE TITLE
pyannote and torch version mismatch

### ISSUE THREAD

**Issue by EarningsCall** [jim60105/docker-whisperX#32]
When running the model, I am seeing these warning messages:

```
Model was trained with pyannote.audio 0.0.1, yours is 3.1.0. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.1+cu118. Bad things might happen unless you revert torch to 1.x.
```

Is this actually a problem?  In practice, I don't see anything wrong with the transcription results (they successfully complete).

**Comment by jim60105** [comment]
Check https://github.com/m-bain/whisperX/issues/258 , should be fine.
WhisperX defines the versions of these packages, and the corresponding requirements should be addressed there.
I am closing this issue as it is beyond my control.
