### ISSUE TITLE
version where you don't uninstall pip plz!

### ISSUE THREAD

**Issue by whillas-yabble** [jim60105/docker-whisperX#38]
Hi,

I'm deploying a docker container and using this image as a base but need to install my own dependencies using pip but i note you uninstall it. Could you build a set of images that don't do this plz!

I'm trying to reinstall it:
```
USER root
RUN apt-get update && apt-get install -y python3-pip
```
which really adds to the build time. How much space are you saving by removing pip anyway?

**Comment by jim60105** [comment]
I removed it mainly for _SECURITY_ reasons, not for space.

If you have expansion needs, I recommend extracting the specific files from the image to meet your needs, similar to how I used ffmpeg.
https://github.com/jim60105/docker-whisperX/blob/bd3cf70f8a7bc019f01cf82c835e7d03c29fcfc9/Dockerfile#L89

If you want to get the program and dependencies, it's located under `/home/1001/.local`.
The align models and whisper models are located under `/.cache`.
Please check the `no_model` stage and the `final` stage of the Dockerfile to see how it is constructed.

**Comment by whillas-yabble** [comment]
Thanks I'll have a look.

Whats the security issue with pip?

**Comment by jim60105** [comment]
Minimizes the attack surface.
It's recommand to throw any unnecessary tools from the final image, including the shell if possible.
Refer to the concept of [distroless](https://github.com/GoogleContainerTools/distroless).

**Comment by whillas-yabble** [comment]
yeah, but, this is for people running the command line tool from within the docker image. Once you remove pip and setuptools it can't be usd for anything else i.e. serving the model... so how is there anyway anyone can get access to the "attack surface" in the few minutes that someone is running this from a command prompt?

**Comment by jim60105** [comment]
I don't know, I'm not a hacker,
Even if what I patched was already almost impossible to attack, it wouldn't be a problem.

If you use it as an end product, this product surely does not need pip at the runtime, so I can throw it without burden.

If you need to expand it, you already need an additional Dockerfile and docker build, then it won't be a problem for you either.

**Comment by jim60105** [comment]
I'm not sure what you mean by "serving the model." 
Basically, you shouldn't run the command line manually inside my image.
Containers are cattle, unlike virtual machines which are pets.

**Comment by whillas-yabble** [comment]
but this is how you recommend one uses it in the Readme.md
```
docker run --gpus all -it -v ".:/app" ghcr.io/jim60105/whisperx:base-en     -- --output_format srt audio.mp3
```
... so where is the room to hack?

People can't use it as an end product because you mutilate the base python image so its only good for the above use case... which I have no idea how you'd productionize a docker run command. I'm trying to integrate it into Dagster which is an orchestration platform.

Its way to complicated to extent as well. This must be one of the most complex Dockerfiles I've ever worked with. I ended up writing my own from scratch. Its a much larger image but doesn't cost developer time to setup and debug and is easy for the next person to understand which are both far more important in business. 

I only intend these comments to be feedback if you want your work to be more widely used since you obviously have spend time thinking about it.

Thanks anyway

**Comment by jim60105** [comment]
Yes, it is one of the most complex dockerfile I have ever written.
Why does it look like this? I didn't make it like this to mess with people.

My goal is to achieve the functionality mentioned in the readme and trigger CI weekly on GitHub Free runner while synchronizing builds nearly 200 docker images with a capacity of 10GB, as well as reusing docker layers as much as possible and manage cache write and read order to reduce build failures, and decrease image size and build time.
Then, for my personal preference, implement it according to best practices and industry standards/policies as much as possible.

The "ease of reading the dockerfile" is not the main consideration; as long as I can maintain it, there's no problem.
I've also provided instructions on how to extend it above; in my opinion, there are no technical issues with that.

If you think it doesn't meet your "functional and simple" requirements, you can always write one yourself.
This is not an official image repository or anything like that; I have no intention nor ability to make it meet everyone's needs.

Thank you for your feedback, but this is in line with my design.
