### ISSUE TITLE
Docker image with Whisperx ASR API endpoint

### ISSUE THREAD

**Issue by ga-it** [jim60105/docker-whisperX#39]
Thanks for the work in setting up your dockerised solution.

Would it be possible to add an option to have the docker image offer an OpenAI compatible STT endpoint?

Effectively that could be a merge of whisperx with the popular whisper docker image https://github.com/ahmetoner/whisper-asr-webservice

Or this
https://github.com/matatonic/openedai-whisper

This appears to be a whisperx effort but it is not maintained:

https://github.com/tijszwinkels/whisperX-api

It would be essential to conform to the OpenAI API definition but potentially with extra Whisperx parameters

**Comment by jim60105** [comment]
This exceeds the goals I set for this project, and I don't have the capacity to support it.

I welcome anyone to fork and implement their own, as long as it complies with my (MIT) and WhisperX (BSD-4) licenses.
