### ISSUE TITLE
Docker build is failing 

### ISSUE THREAD

**Issue by C0RE1312** [jim60105/docker-whisperX#40]
Suddenly the docker build is failing :(

 > [load_whisper 1/2] RUN python3 -c 'from whisperx.vad import load_vad_model; load_vad_model("cpu");':
1.621
1.621 A module that was compiled using NumPy 1.x cannot be run in
1.621 NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
1.621 versions of NumPy, modules must be compiled with NumPy 2.0.
1.621 Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
1.621
1.621 If you are a user of the module, the easiest solution will be to
1.621 downgrade to 'numpy<2' or try to upgrade the affected module.
1.621 We expect that some modules will need time to support NumPy 2.
1.621
1.621 Traceback (most recent call last):  File "<string>", line 1, in <module>
1.621   File "/home/1001/.local/lib/python3.11/site-packages/whisperx/__init__.py", line 1, in <module>
1.621     from .transcribe import load_model
1.621   File "/home/1001/.local/lib/python3.11/site-packages/whisperx/transcribe.py", line 7, in <module>
1.621     import torch
1.621   File "/home/1001/.local/lib/python3.11/site-packages/torch/__init__.py", line 1382, in <module>
1.621     from .functional import *  # noqa: F403
1.621   File "/home/1001/.local/lib/python3.11/site-packages/torch/functional.py", line 7, in <module>
1.621     import torch.nn.functional as F
1.621   File "/home/1001/.local/lib/python3.11/site-packages/torch/nn/__init__.py", line 1, in <module>
1.621     from .modules import *  # noqa: F403
1.621   File "/home/1001/.local/lib/python3.11/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
1.621     from .transformer import TransformerEncoder, TransformerDecoder, \
1.621   File "/home/1001/.local/lib/python3.11/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
1.621     device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
1.621 /home/1001/.local/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
1.621   device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
14.32 /home/1001/.local/lib/python3.11/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
14.32   torchaudio.set_audio_backend("soundfile")
14.96 Traceback (most recent call last):
14.96   File "<string>", line 1, in <module>
14.96   File "/home/1001/.local/lib/python3.11/site-packages/whisperx/__init__.py", line 1, in <module>
14.96     from .transcribe import load_model
14.96   File "/home/1001/.local/lib/python3.11/site-packages/whisperx/transcribe.py", line 10, in <module>
14.96     from .asr import load_model
14.96   File "/home/1001/.local/lib/python3.11/site-packages/whisperx/asr.py", line 13, in <module>
14.96     from .vad import load_vad_model, merge_chunks
14.96   File "/home/1001/.local/lib/python3.11/site-packages/whisperx/vad.py", line 9, in <module>
14.96     from pyannote.audio import Model
14.96   File "/home/1001/.local/lib/python3.11/site-packages/pyannote/audio/__init__.py", line 29, in <module>
14.96     from .core.inference import Inference
14.96   File "/home/1001/.local/lib/python3.11/site-packages/pyannote/audio/core/inference.py", line 49, in <module>
14.96     class Inference(BaseInference):
14.96   File "/home/1001/.local/lib/python3.11/site-packages/pyannote/audio/core/inference.py", line 533, in Inference
14.96     missing: float = np.NaN,
14.96                      ^^^^^^
14.96   File "/home/1001/.local/lib/python3.11/site-packages/numpy/__init__.py", line 397, in __getattr__
14.96     raise AttributeError(
14.96 AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.. Did you mean: 'nan'?
------
Dockerfile:165
--------------------
 163 |
 164 |     # Preload vad model
 165 | >>> RUN python3 -c 'from whisperx.vad import load_vad_model; load_vad_model("cpu");'
 166 |
 167 |     # Preload fast-whisper
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -c 'from whisperx.vad import load_vad_model; load_vad_model(\"cpu\");'" did not complete successfully: exit code: 1

**Comment by C0RE1312** [comment]
Update: https://github.com/pyannote/pyannote-audio/pull/1725

**Comment by jim60105** [comment]
The build failed due to some breaking changes in numpy 2.0.
We will remain on version <2 as the upgrade needs to be completed on the WhisperX side.

https://github.com/m-bain/whisperX/blob/f2da2f858e99e4211fe4f64b5f2938b007827e17/setup.py#L24

**Comment by jim60105** [comment]
I will close this issue later if this CI runs build successfully.
https://github.com/jim60105/docker-whisperX/actions/runs/9582397119

Re-open this issue or create a new one if WhisperX updated in the future.

**Comment by jim60105** [comment]
Well, I forgot about UBI😅 
https://github.com/jim60105/docker-whisperX/actions/runs/9582713347
