### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Rohandud** [jim60105/docker-whisperX#45]
```
rohan@asus:/instagram/whisper/docker-whisperX$ docker run --gpus all -it -v ".:/app" -v whisper_cache:/.cache ghcr.io/jim60105/whisperx:latest -- --model large-v3 --language en --output_format srt audio.mp3
Unable to find image 'ghcr.io/jim60105/whisperx:latest' locally
latest: Pulling from jim60105/whisperx
e4fff0779e6d: Already exists 
d97016d0706d: Already exists 
53db1713e5d9: Already exists 
a8cd795d9ccb: Already exists 
de3ba92de392: Already exists 
4f4fb700ef54: Already exists 
2469a54eb180: Already exists 
a5989e678db4: Already exists 
dbeac7169394: Already exists 
a25dbba2d9fe: Already exists 
46fab96797bf: Already exists 
a1b7baaeb599: Already exists 
1cd997c469d8: Already exists 
1e74ff3ccf4a: Already exists 
74e940b38918: Already exists 
Digest: sha256:4ff390b2315d8c664ac35873014a17a07bd05d3ebbafd44d6de3d433e7ddad04
Status: Downloaded newer image for ghcr.io/jim60105/whisperx:latest
/home/1001/.local/lib/python3.11/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
torchvision is not available - cannot save figures
preprocessor_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 340/340 [00:00<00:00, 1.44MB/s]
config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.39k/2.39k [00:00<00:00, 7.56MB/s]
vocabulary.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.07M/1.07M [00:01<00:00, 794kB/s]
tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.48M/2.48M [00:02<00:00, 1.01MB/s]
model.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.09G/3.09G [04:40<00:00, 11.0MB/s]
100%|██████████████████████████████████████| 16.9M/16.9M [00:51<00:00, 346kiB/s]███████████████████████████████████████████████████████████████████████████████████████| 3.09G/3.09G [04:40<00:00, 10.7MB/s]
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.2.2+cu121. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
Downloading: "https://download.pytorch.org/torchaudio/models/wav2vec2_fairseq_base_ls960_asr_ls960.pth" to /.cache/torch/hub/checkpoints/wav2vec2_fairseq_base_ls960_asr_ls960.pth
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 360M/360M [00:33<00:00, 11.4MB/s]
>>Performing alignment...
Traceback (most recent call last):
  File "/home/1001/.local/bin/whisperx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/1001/.local/lib/python3.11/site-packages/whisperx/transcribe.py", line 227, in cli
    writer(result, audio_path, writer_args)
  File "/home/1001/.local/lib/python3.11/site-packages/whisperx/utils.py", line 205, in __call__
    with open(output_path, "w", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: './audio.srt'
rohan@asus:/instagram/whisper/docker-whisperX$ docker run --gpus all -it -v ".:/app" -v whisper_cache:/.cache ghcr.io/jim60105/whisperx:latest -- --model large-v3 --language en --output_format srt audio.mp3
/home/1001/.local/lib/python3.11/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
torchvision is not available - cannot save figures
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.2.2+cu121. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
>>Performing alignment...
Traceback (most recent call last):
  File "/home/1001/.local/bin/whisperx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/1001/.local/lib/python3.11/site-packages/whisperx/transcribe.py", line 227, in cli
    writer(result, audio_path, writer_args)
  File "/home/1001/.local/lib/python3.11/site-packages/whisperx/utils.py", line 205, in __call__
    with open(output_path, "w", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: './audio.srt'
rohan@asus:/instagram/whisper/docker-whisperX$ 


```

**Comment by jim60105** [comment]
This image follows best practices by using a non-root user.

It is running as 1001:0
Please confirm it has permission to write to your current directory.

**Comment by Rohandud** [comment]
rohan@asus:~/instagram/whisper/docker-whisperX$ l
audio.mp3        Dockerfile  load_align_model.py  README.md       whisperX/
docker-bake.hcl  LICENSE     output_audio.mp3     ubi.Dockerfile
rohan@asus:~/instagram/whisper/docker-whisperX$ ls -ld .
drwxrwxr-x 6 rohan rohan 4096 Nov  3 15:37 .
rohan@asus:~/instagram/whisper/docker-whisperX$ id
uid=1000(rohan) gid=1000(rohan) groups=1000(rohan),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),107(input),122(lpadmin),135(lxd),136(sambashare),142(libvirt),999(docker)
rohan@asus:~/instagram/whisper/docker-whisperX$

**Comment by Rohandud** [comment]
i tried 

rohan@asus:/instagram/whisper/docker-whisperX$ docker run --gpus all -it -v ".:/app" ghcr.io/jim60105/whisperx:base-en     -- --output_dir /tmp/. --output_format srt audio.mp3
/home/1001/.local/lib/python3.11/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
torchvision is not available - cannot save figures
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.2.2+cu121. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
>>Performing alignment...
rohan@asus:/instagram/whisper/docker-whisperX$ ll /tmp
total 136
drwxrwxrwt 31 root  root  16384 Nov  3 21:43 ./
drwxr-xr-x 21 root  root   4096 Oct 21 19:37 ../
drwxrwxrwt  2 root  root   4096 Nov  3 21:35 .font-unix/
-rw-------  1 rohan rohan     0 Nov  3 21:35 gdm3-config-err-OiySIf
drwxrwxrwt  2 root  root   4096 Nov  3 21:35 .ICE-unix/
drwx------  2 rohan rohan  4096 Nov  3 21:36 .org.chromium.Chromium.2BetBN/
drwx------  2 rohan rohan  4096 Nov  3 21:36 .org.chromium.Chromium.62e8lc/
drwx------  2 rohan rohan  4096 Nov  3 21:35 .org.chromium.Chromium.cqwzym/
drwx------  2 rohan rohan  4096 Nov  3 21:35 .org.chromium.Chromium.dNrmkL/
drwx------  2 rohan rohan  4096 Nov  3 21:35 .org.chromium.Chromium.G9FPOV/
drwx------  2 rohan rohan  4096 Nov  3 21:35 .org.chromium.Chromium.it9t29/
drwx------  2 rohan rohan  4096 Nov  3 21:36 .org.chromium.Chromium.ZaHLVx/
drwx------  2 rohan rohan  4096 Nov  3 21:41 pyright-5864-K6lZu3oSjlEx/
drwx------  2 rohan rohan  4096 Nov  3 21:41 pyright-5864-UhIZmGH3a3sl/
drwx------  2 rohan rohan  4096 Nov  3 21:42 pyright-5864-Xudr51LAxMVg/
drwxrwxr-x  3 rohan rohan  4096 Nov  3 21:41 python-languageserver-cancellation/
drwx------  6 root  root   4096 Nov  3 21:40 snap-private-tmp/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-bluetooth.service-yR9JrB/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-bolt.service-4xhham/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-colord.service-u57mkO/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-fwupd.service-fX6lgs/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-ModemManager.service-q8YDdz/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-power-profiles-daemon.service-LhaLHv/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-switcheroo-control.service-xw3G4c/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-systemd-logind.service-s7i9Hu/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-systemd-oomd.service-ThcsNT/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-systemd-resolved.service-uxEMdJ/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-systemd-timesyncd.service-Fv5Zet/
drwx------  3 root  root   4096 Nov  3 21:35 systemd-private-95e2150e0abe4b049b8bca032c44fc8c-upower.service-OfCNHK/
drwxrwxrwt  2 root  root   4096 Nov  3 21:35 .Test-unix/
drwxrwxrwt  2 root  root   4096 Nov  3 21:35 .X11-unix/
drwxrwxrwt  2 root  root   4096 Nov  3 21:35 .XIM-unix/
rohan@asus:/instagram/whisper/docker-whisperX$ 






###Making the output dir to /tmp worked but cant find srt file there, im a new to docker

**Comment by jim60105** [comment]
### Step 1: Create the directory structure

First, we'll create the directory structure you specified:

```bash
mkdir ~/srt
```

This command creates a new directory named "srt" in your home directory (~).

### Step 2: Change ownership

Next, we'll change the ownership of the newly created directory:

```bash
sudo chown 1000:0 ~/srt
```

This command changes the owner of the directory to user ID 1000 and group ID 0 (root). Note that you need sudo privileges to perform this operation.

### Step 3: Set permissions

Now, let's set the permissions for the directory:

```bash
sudo chmod 775 ~/srt
```

This sets read, write, and execute permissions for the owner, read and execute permissions for the group, and read and execute permissions for others.

### Step 4: Change to the directory

Let's navigate to the newly created directory:

```bash
cd ~/srt
```

This command changes your current working directory to ~/srt.

### Step 5: Run the Docker command

Finally, let's execute the Docker command:

```bash
docker run --gpus all -it -v ".:/app" -v whisper_cache:/.cache ghcr.io/jim60105/whisperx:latest -- --model large-v3 --language en --output_format srt audio.mp3
```

Let's break down this Docker command:

- `docker run`: This starts a new Docker container.
- `--gpus all`: This allocates all available GPUs to the container.
- `-it`: This keeps STDIN open and allocates a pseudo-TTY.
- `-v ".:/app"`: This mounts the current directory (.) to /app in the container.
- `-v whisper_cache:/.cache`: This mounts a volume named whisper_cache to /.cache in the container.
- `ghcr.io/jim60105/whisperx:latest`: This specifies the Docker image to use.
- `--`: This separates the Docker run options from the command to be executed in the container.
- `--model large-v3 --language en --output_format srt audio.mp3`: These are the arguments passed to the WhisperX application inside the container.

### Explanation of what happened:

1. We created a directory named "srt" in your home folder.
2. We changed the ownership of this directory to user ID 1000 and group ID 0.
3. We set the permissions of the directory to 775, allowing full control for the owner and read/write access for others.
4. We navigated into the newly created directory.
5. We started a Docker container based on the WhisperX image.
6. Inside the container, we mounted our current directory and a whisper_cache volume.
7. We instructed the WhisperX application to use the large-v3 model, English language, and output format SRT.
8. We provided an input audio file named "audio.mp3".

This setup allows you to run the WhisperX application on your local machine, utilizing GPU acceleration if available, and process audio files stored in your current directory.

**Comment by ethanfel** [comment]
> ### Step 1: Create the directory structure
> 
> First, we'll create the directory structure you specified:
> 
> mkdir ~/srt
> 
> This command creates a new directory named "srt" in your home directory (~).
> ### Step 2: Change ownership
> 
> Next, we'll change the ownership of the newly created directory:
> 
> sudo chown 1000:0 ~/srt
> 
> This command changes the owner of the directory to user ID 1000 and group ID 0 (root). Note that you need sudo privileges to perform this operation.
> ### Step 3: Set permissions
> 
> Now, let's set the permissions for the directory:
> 
> sudo chmod 775 ~/srt
> 
> This sets read, write, and execute permissions for the owner and the group, and read and execute permissions for others.
> ### Step 4: Change to the directory
> 
> Let's navigate to the newly created directory:
> 
> cd ~/srt
> 
> This command changes your current working directory to ~/srt.
> ### Step 5: Run the Docker command
> 
> Finally, let's execute the Docker command:
> 
> docker run --gpus all -it -v ".:/app" -v whisper_cache:/.cache ghcr.io/jim60105/whisperx:latest -- --model large-v3 --language en --output_format srt audio.mp3
> 
> Let's break down this Docker command:
> 
>     * `docker run`: This starts a new Docker container.
> 
>     * `--gpus all`: This allocates all available GPUs to the container.
> 
>     * `-it`: This keeps STDIN open and allocates a pseudo-TTY.
> 
>     * `-v ".:/app"`: This mounts the current directory (.) to /app in the container.
> 
>     * `-v whisper_cache:/.cache`: This mounts a volume named whisper_cache to /.cache in the container.
> 
>     * `ghcr.io/jim60105/whisperx:latest`: This specifies the Docker image to use.
> 
>     * `--`: This separates the Docker run options from the command to be executed in the container.
> 
>     * `--model large-v3 --language en --output_format srt audio.mp3`: These are the arguments passed to the WhisperX application inside the container.
> 
> 
> ### Explanation of what happened:
> 
>     1. We created a directory named "srt" in your home folder.
> 
>     2. We changed the ownership of this directory to user ID 1000 and group ID 0.
> 
>     3. We set the permissions of the directory to 775, allowing full control for the owner and read/write access for others.
> 
>     4. We navigated into the newly created directory.
> 
>     5. We started a Docker container based on the WhisperX image.
> 
>     6. Inside the container, we mounted our current directory and a whisper_cache volume.
> 
>     7. We instructed the WhisperX application to use the large-v3 model, English language, and output format SRT.
> 
>     8. We provided an input audio file named "audio.mp3".
> 
> 
> This setup allows you to run the WhisperX application on your local machine, utilizing GPU acceleration if available, and process audio files stored in your current directory.

I have the exact samz issue and this is not working even wih a root docker

**Comment by ratbunch** [comment]
> I have the exact same issue and this is not working even wih a root docker

I had to 777 it to get it work. Just did it for a dedicated output folder the  directory i run the docker from then used --output_dir <srt_dir>

in the docker command. This fixed my issue. Not sure why. but it did.
