### ISSUE TITLE
Why are there language specific Docker images?

### ISSUE THREAD

**Issue by edsu** [jim60105/docker-whisperX#46]
I understand why you have model specific containers, so that the model file can be part of the image itself, and you want have to download the file each time it runs. But why do you want to have model + language specific containers? The language is a runtime option that doesn't incur any downloading right? Couldn't the container be given the language to use as an argument, like the input file?

Thank you for your work on this!

**Comment by jim60105** [comment]
The WhisperX project uses phoneme ASR alignment models for processing alignment, and these models are downloaded during runtime. They will be downloaded the first time they are used and then cached.
https://github.com/m-bain/whisperX/tree/main?tab=readme-ov-file#other-languages

You can see the models used for each language [here](https://github.com/jim60105/docker-whisperX/blob/master/load_align_model.py).

**Comment by edsu** [comment]
Thanks, I didn't know WhisperX did this!
